### ISSUE TITLE
Gem doesn't load.

### ISSUE THREAD

**Issue by jespinoza57** [soundcloud/soundcloud-ruby#16]
uninitialized constant SoundcloudController::Soundcloud

this is the error i get.

when i include "require 'soundcloud'" in my controller i get this error 

cannot load such file -- soundcloud

and i have it in my gemfile and i've already bundled it.

Thanks.

**Comment by dajwill** [comment]
Same here

**Comment by dajwill** [comment]
I was able to fix this error by using a lowercase 'c' in Soundcloud

client = Soundcloud.new
