### ISSUE TITLE
OpenSSL Error when authenticating using OAuth User Credentials Flow

### ISSUE THREAD

**Issue by benwells** [soundcloud/soundcloud-ruby#28]
The following error occurs when trying to create a new SoundCloud client using the OAuth User Credentials Flow.  I would like to authenticate with my own account via username and password, but constantly receive this error.

/Users/gdgd/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
  from /Users/gdgd/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
  from /Users/gdgd/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:67:in `timeout'
  from /Users/gdgd/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `connect'
  from /Users/gdgd/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
  from /Users/gdgd/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:852:in `start'
  from /Users/gdgd/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1369:in `request'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/httparty-0.13.1/lib/httparty/request.rb:93:in `perform'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/httparty-0.13.1/lib/httparty.rb:521:in `perform_request'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/httmultiparty-0.3.14/lib/httmultiparty.rb:103:in `post'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/soundcloud-0.3.2/lib/soundcloud/client.rb:130:in `block in exchange_token'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/soundcloud-0.3.2/lib/soundcloud/client.rb:145:in `call'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/soundcloud-0.3.2/lib/soundcloud/client.rb:145:in `handle_response'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/soundcloud-0.3.2/lib/soundcloud/client.rb:129:in `exchange_token'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/soundcloud-0.3.2/lib/soundcloud/client.rb:20:in `initialize'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/soundcloud-0.3.2/lib/soundcloud.rb:14:in `new'
  from /Users/gdgd/.rvm/gems/ruby-2.1.0/gems/soundcloud-0.3.2/lib/soundcloud.rb:14:in `new'

**Comment by pre** [comment]
If you have installed Ruby with RVM as a binary and OpenSSL with Homebrew, then there's a mismatch between these two. Try installing Ruby with sources, eg. `rvm install 2.2.0 --disable-binary`

See this issue: http://stackoverflow.com/questions/30901864/troubleshooting-ssl-certificates-ruby-mac-os-x-yosemite/33035529#33035529

**Comment by raggi** [comment]
The primary difference between openssl-osx-ca and solutions such as rvm or brews "bootstrap" for ca certs is that openssl-osx-ca **keeps your ca certs up to date**! (it installs a cron that runs once an hour)

This is more important that I think users even realize. CA certs *do expire* and a bunch expired quite recently. Many users who've just gone and dropped arbitrary curl bundles into arbitrary directories have expired certs in their infrastructure and can't validate some connections.

**Comment by adwacoin** [comment]
On Windows 10, running lastest Ruby 2.2.4, managed to fix by following this instruction:
https://gist.github.com/fnichol/867550
This entails saving this file http://curl.haxx.se/ca/cacert.pem to your system.
Then I ran this on the console -> set SSL_CERT_FILE=C:\Ruby22-x64\lib\ruby\2.2.0\rubygems\ssl_certs\cacert.pem (I copied file here, also make this permanent to your system).
This at least got rid of any SSL errors.
