### ISSUE TITLE
Delete playlist

### ISSUE THREAD

**Issue by musixite** [soundcloud/soundcloud-ruby#45]
Hello there,

I'm really surprised that the api doesn't offer a delete method for playlists. Did I miss something?

- Vincent

**Comment by therealaldo** [comment]
Hey Vincent, 

I used the api about a month ago and from my experience, they had no delete functionality for playlists from what I saw.

**Comment by musixite** [comment]
I actually tried using the same delete method than a track and it works:
        SoundcloudAPI.delete("/playlists/#{self.soundcloud_id}")

Thanks!
- Vincent
