### ISSUE TITLE
User followers_count and followings_count always returns 0

### ISSUE THREAD

**Issue by jamesfzhang** [soundcloud/soundcloud-ruby#47]
Seems like a recent change,but these 2 counts return 0 for all users.

**Comment by grobie** [comment]
Which endpoint? Can you provide an example query?

**Comment by jamesfzhang** [comment]
```ruby
client = Soundcloud.new(access_token: s_token)
result = client.get('/me')
puts result['followers_count']
puts result['followings_count']
```

**Comment by grobie** [comment]
Thank you for reporting. I informed the team.

**Comment by jamesfzhang** [comment]
Thanks for the speedy response.

**Comment by alonpeer** [comment]
It appears that this is yet another endpoint that we need to strangler. I'll work on a PR for that.

CC @soundcloud/activities

**Comment by alonpeer** [comment]
Hi @jamesfzhang,

We've found the fixed the issue. Thanks for reporting!
