### ISSUE TITLE
SoundCloud search API returning non-matching results

### ISSUE THREAD

**Issue by kevinebaugh** [soundcloud/soundcloud-ruby#48]
Users of the [SoundCloud Channel](https://ifttt.com/soundcloud) on IFTTT have been reporting errant results for their "New track from search" Recipes. Here are some examples:

>Argh @IFTTT  going crazy! Please stop it! [screenshot](https://pbs.twimg.com/media/CbgK0uVXIAQQ8ki.png)
> — [@KevinLundDK](https://twitter.com/KevinLundDK/status/700321716338298880/photo/1)

---
>@FrasSpaz I'm aware that there is an issue; I'm not even listening to these tracks. @SoundCloud and @IFTTT are having issues. Grrrrr...
>— [@JeffBoulton](https://twitter.com/JeffBoulton/statuses/700409201974095872)
>@FrasSpaz I have an @IFTTT recipe set up to Tweet any @SoundCloud track that I publicly like.  Somehow, there is an issue with this recipe.
> — [@JeffBoulton](https://twitter.com/JeffBoulton/status/700410639345266688)

---

>@IFTTT getting a ton of emails with one recipe I made even after I turned it off. Something going on?
>— [@pencilvspixel](http://twitter.com/pencilvspixel/statuses/700383029609377792)

---

>@IFTTT My Soundcloud search for trigger started finding errant results and just ate through my SMS limit for the month. Can you help?
— [@jamesej](http://twitter.com/jamesej/statuses/700731606395301889)

---

Here is a simple script using the SoundCloud API that is also returning errant results: 

    require 'soundcloud'

    client = Soundcloud.new(:client_id => '********************************')

    tracks = client.get('/tracks', :q => 'notgoingtomatchanytracks', order: 'created_at')

    puts "Found #{tracks.count} tracks \n\n"

    tracks.each do |t|
        puts "Title: #{t.title}"
        puts "\n"
    end

There aren't any results matching this query: https://soundcloud.com/search?q=notgoingtomatchanytracks

But here is the output from running that script above:

    Title: Hilang | URL: https://soundcloud.com/ilham-winar/hilang
    Title: Nonstop - Vinh Ngày Nắng - DJ-TMC | URL: https://soundcloud.com/ho-ng-l-m-756667259/nonstop-vinh-ngay-nang-dj-tmc
    Title: Call Bee - Put Your Handz Up 4 Detroit (Original Mix)DEMO!!! | URL: https://soundcloud.com/iblak/call-bee-put-your-handz-up-4-detroit-original-mixdemo
    Title: RYM Live Selection | URL: https://soundcloud.com/juliette1994/rym-live-selection
    Title: Lead Neck Pickup | URL: https://soundcloud.com/user-619995529/lead-neck-pickup-1
    Title: Nguyenbang Beautiful In White Group2 | URL: https://soundcloud.com/user-742726752/nguyenbang-beautiful-in-white-group2
    Title: Abstract | URL: https://soundcloud.com/stratphonics/abstract
    Title: BAB2 Ft PAPSON AFRICA By 4G MusiC | URL: https://soundcloud.com/4g-music/bab2-ft-papson-africa-by-4g-music
    Title: MISSION BEAT | URL: https://soundcloud.com/kghmix/mission-beat

**Comment by grobie** [comment]
Thanks for reporting. I contacted the team.

**Comment by kevinebaugh** [comment]
Thanks @grobie!

**Comment by grobie** [comment]
This has been fixed. Thanks again for reporting.

**Comment by kevinebaugh** [comment]
Awesome, thanks again @grobie.
