### ISSUE TITLE
HTTP status: 504 Gateway Timeout on upload after refreshing token

### ISSUE THREAD

**Issue by simianarmy** [soundcloud/soundcloud-ruby#50]
After a long period of error-free usage, I started seeing this error in my logs.
It looks like when an upload takes place, the client is sent a 401 Unauthorized so it reauthorizes with a POST /oauth2/token.
That response returns a refresh token and access token and the gem looks like it restarts the upload process.
That hangs for a long time and eventually times out with the 504.

I don't see anything on SO about it.

I create the client this way:
```
@client = SoundCloud.new({
          :client_id     => cnf['client_id'],
          :client_secret => cnf['client_secret'],
          :username      => cnf['username'],
          :password      => cnf['password']
        })

```
The failing response is detailed below:
`starting SSL for api.soundcloud.com:443...
SSL established
<- "POST /me/tracks HTTP/1.1\r\nUser-Agent: SoundCloud Ruby Wrapper 0.13.7\r\nContent-Type: multipart/form-data; boundary=-----------RubyMultipartPost\r\nContent-Length: 35544\r\nConnection: close\r\nHost: api.soundcloud.com\r\n\r\n"
-> "HTTP/1.1 504 Gateway Timeout\r\n"
-> "Content-Type: text/html\r\n"
-> "Date: Sat, 28 May 2016 17:04:57 GMT\r\n"
-> "Last-Modified: Fri, 16 May 2014 10:00:00 GMT\r\n"
-> "Server: am/2\r\n"
-> "Content-Length: 2203\r\n"
-> "Connection: close\r\n"
-> "\r\n"
reading 2203 bytes...
-> ""
-> "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n<html lang=\"en\">\n  <head>\n    <meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\" />\n    <title>We were unable to process your request in time - SoundCloud</title>\n    <style type=\"text/css\">\n      body {\n        background-color: #fff;\n        background-image : url(https://soundcloud-support.s3.amazonaws.com/images/downtime-bg.png);\n        background-repeat: repeat-x;\n      }\n      #maintenance {\n        width: 325px;\n        height : 180px;\n        background-color : transparent;\n        background-image : url(https://soundcloud-support.s3.amazonaws.com/images/reload-huge.png);\n        background-position: top left;\n        background-repeat: no-repeat;\n        margin : 150px auto 0 auto;\n        color: #666;\n        font-family: \"Lucida Grande\", Helvetica, Arial, sans-serif;\n        font-size: 13px;\n        position: relative;\n        padding: 125px 0 0 200px;\n      }\n      #maintenance h1 {\n        font-weight: normal;\n        font-size: 28px;\n        color: #06c;\n      }\n      #maintenance a {\n        color: #f30;\n        text-decoration: none;\n      }\n    </style>\n  </head>\n  <body>\n    <div id=\"maintenance\">\n      <h1>\n      Yikes, we were unable\n      <br />\n      to process your request\n      <br />\n      in time.\n      </h1>\n      <span>\n        Please reload the page or try again in a moment.\n        <br />\n        Please check <a href=\"http://status.soundcloud.com/\"><strong>our Status page</strong></a> for more details as they come in.\n      </span>\n    </div>\n    <script>\n      window._gaq = window._gaq || [];\n      _gaq.push(['_setAccount', 'UA-2519404-1']);\n      _gaq.push(['_trackPageview']);\n      _gaq.push(['_trackEvent', '504', 'ampelmann', window.location.toString()]);\n\n      (function() {\n        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n      })();\n    </script>\n  </body>\n</html>\n"
read 2203 bytes
Conn close`

**Comment by grobie** [comment]
Thanks for the report! I'll ask the team.

**Comment by simianarmy** [comment]
If it helps, it turns out that the file uploads successfully but since an exception is thrown by the gem, I do not get the track data.  It also takes a long time before the 504 returns.

**Comment by denis-soundcloud** [comment]
Hi Marc,

Uploading a track should be done by making a POST request to `/tracks`, rather than to `/me/tracks`. The latter is unsupported and undocumented, and will likely not stay around.

Do let us know if you have the same problem with the `/tracks` endpoint!

Denis
