### ISSUE TITLE
Upload returns 401, but track gets uploaded

### ISSUE THREAD

**Issue by jamesfzhang** [soundcloud/soundcloud-ruby#51]
I noticed this because we retry uploads in the case of an error, but I noticed the same track gets uploaded multiple times because of the retries. Turns out the call to `client.post('/tracks')` causes a `HTTP status: 401 Unauthorized` exception, but the track gets uploaded properly to SoundCloud.

**Comment by denis-soundcloud** [comment]
Hi @jamesfzhang,

Thanks for reporting this issue! We have rolled out a fix, so this problem will no longer occur. If it does, please do let us know.

Denis
