### ISSUE TITLE
Cannot install gem because v0.3.3 is not available

### ISSUE THREAD

**Issue by KO527** [soundcloud/soundcloud-ruby#56]
My-MacBook-Pro:GodsofRiotry Project$ sudo gem install soundcloud -v 0.3.3
ERROR:  Could not find a valid gem 'soundcloud' (= 0.3.3) in any repository
ERROR:  Possible alternatives: soundcloud

Obviously, This gem was not uploaded to allow other developers to use it.

**Comment by grobie** [comment]
The rubygems credentials issue has been sorted out and v0.3.3 is now available: https://rubygems.org/gems/soundcloud

Thank you for your patience.
